services:
  base:
    image: bennettp123/sample-base:${REF}
    build:
      dockerfile: ./Dockerfile.base
      args:
        - REF

  one:
    image: bennettp123/sample-one:${REF}
    build:
      dockerfile: ./Dockerfile.1
      args:
        - REF
      x-bake:
        contexts:
          bennettp123/sample-base:local-build: target:base
        pull: true

  two:
    image: bennettp123/sample-two:${REF}
    build:
      dockerfile: ./Dockerfile.2
      args:
        - REF
      x-bake:
        contexts:
          bennettp123/sample-base:local-build: target:base
        pull: true

  three:
    image: bennettp123/sample-three:${REF}
    build:
      dockerfile: ./Dockerfile.3
      args:
        - REF
      x-bake:
        contexts:
          bennettp123/sample-base:local-build: target:base
        pull: true
