services:
  one:
    image: bennettp123/sample-one:latest
    build:
      context: .
      dockerfile: ./Dockerfile.1
  two:
    image: bennettp123/sample-two:latest
    build:
      context: .
      dockerfile: ./Dockerfile.2
  three:
    image: bennettp123/sample-three:latest
    build:
      context: .
      dockerfile: ./Dockerfile.3
  
