name: bake

on:
  push:
    branches:
      - main

jobs:
  targets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/bake-action/issues/87#issuecomment-1184659151
      - name: Create matrix
        id: targets
        run: |
          echo "matrix=$(docker buildx bake --print | jq -cr '.group.default.targets')" >> "${GITHUB_OUTPUT}"
      - name: Show matrix
        run: |
          echo ${{ steps.targets.outputs.matrix }}
    outputs:
      matrix: ${{ steps.targets.outputs.matrix }}

  bake:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        target: ${{ fromJson(needs.targets.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          pull: true
          push: true
          targets: ${{ matrix.target }}
          set: |
            *.cache-from=type=gha,scope=build-${{ matrix.target }}
            *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max
